version: '3.8'

services:
  # Development version with hot reload
  image-optimization-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: image-optimization-dev
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - UV_THREADPOOL_SIZE=16
      - SHARP_CACHE_MEMORY=2048
      - SHARP_CONCURRENCY=4
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      # Mount node_modules as volume to avoid conflicts
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - dev-network
    command: npm run start:debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  # Optional: Development database for testing
  postgres-dev:
    image: postgres:15-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: image_optimization_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - database

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - dev-network
    profiles:
      - cache

volumes:
  node_modules:
  postgres_dev_data:
  redis_dev_data:

networks:
  dev-network:
    driver: bridge